name: dev-infra

include:
  - compose/postgres.yaml
  - compose/mongodb.yaml
  - compose/loki.yaml
  - compose/otel-collector.yaml
  - compose/grafana.yaml
  - compose/qwen3.yaml


# ==============================================================================
# Volumes
# ==============================================================================

volumes:

  postgres_data:
    name: dev_postgres_data

  mongodb_data:
    name: dev_mongodb_data

  loki_data:
    name: dev_loki_data

  grafana_data:
    name: dev_grafana_data


# ==============================================================================
# Network
# ==============================================================================

networks:

  dev:
    name: dev_network
    driver: bridge
